package Server.AdminSide;


/**
* Server/AdminSide/AdminInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminInterface.idl
* Monday, May 12, 2025 4:28:54 PM SGT
*/

public interface AdminInterface extends AdminInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminInterface
