package Server.PlayerSide;

/**
* Server/PlayerSide/GameSessionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerInterface.idl
* Tuesday, May 13, 2025 4:19:17 AM SGT
*/

public final class GameSessionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameSession value = null;

  public GameSessionHolder ()
  {
  }

  public GameSessionHolder (GameSession initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameSessionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameSessionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameSessionHelper.type ();
  }

}
