package Server.PlayerSide;


/**
* Server/PlayerSide/GameSessionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerInterface.idl
* Tuesday, May 13, 2025 4:19:17 AM SGT
*/

abstract public class GameSessionHelper
{
  private static String  _id = "IDL:Server/PlayerSide/GameSession:1.0";

  public static void insert (org.omg.CORBA.Any a, GameSession that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameSession extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameSessionHelper.id (), "GameSession");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameSession read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameSessionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameSession value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameSession narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameSession)
      return (GameSession)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameSessionStub stub = new _GameSessionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameSession unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameSession)
      return (GameSession)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameSessionStub stub = new _GameSessionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
