package Server.PlayerSide;


/**
* Server/PlayerSide/GameSessionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerInterface.idl
* Tuesday, May 13, 2025 4:19:17 AM SGT
*/

public interface GameSessionOperations 
{

  // Game management
  void startGame () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NotEnoughPlayersException;
  void endGame () throws Server.Exceptions.SessionNotFoundException, Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;

  // Gameplay
  void guess (String guessingPlayer, char letter) throws Server.Exceptions.NotYourTurnException, Server.Exceptions.WrongGuessException, Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  String getCurrentWordState () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
  String selectWord () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;

  // Player management
  void addPlayer (Server.CommonObjects.User user) throws Server.Exceptions.SessionFullException, Server.Exceptions.PlayerAlreadyInSessionException, Server.Exceptions.UserIsBannedException, Server.Exceptions.LostConnectionException;
  void removePlayer (String playerId) throws Server.Exceptions.NoSuchUserFoundException, Server.Exceptions.LostConnectionException;

  // Status
  String ping (Server.CommonObjects.User user) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NoSuchUserFoundException;
} // interface GameSessionOperations
