package Server.PlayerSide;

/**
* Server/PlayerSide/PlayerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerInterface.idl
* Tuesday, May 13, 2025 4:19:17 AM SGT
*/

public final class PlayerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerInterface value = null;

  public PlayerInterfaceHolder ()
  {
  }

  public PlayerInterfaceHolder (PlayerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerInterfaceHelper.type ();
  }

}
