package Server.PlayerSide;


/**
* Server/PlayerSide/PlayerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerInterface.idl
* Tuesday, May 13, 2025 4:19:17 AM SGT
*/

public interface PlayerInterfaceOperations 
{

  // Authentication
  String login (Server.CommonInterface.CallBackInterface cb, String username, String password) throws Server.Exceptions.LostConnectionException, Server.Exceptions.AlreadyLoggedInException, Server.Exceptions.UserIsBannedException;
  void logout (String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;

  // Lobby management
  GameSession createLobby (Server.CommonObjects.User host, String lobbyName, Server.CommonObjects.GameRules rules) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.SessionAlreadyMadeException;
  GameSession joinLobby (String lobbyId, Server.CommonObjects.User player) throws Server.Exceptions.LostConnectionException, Server.Exceptions.SessionNotFoundException, Server.Exceptions.SessionFullException, Server.Exceptions.PlayerAlreadyInSessionException, Server.Exceptions.UserIsBannedException, Server.Exceptions.NotLoggedInException;
  GameSession randomConnect (Server.CommonObjects.User user) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NoSessionsFoundException, Server.Exceptions.SessionFullException, Server.Exceptions.PlayerAlreadyInSessionException, Server.Exceptions.NotLoggedInException;
  void disconnect (String sessionId, String playerId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.SessionNotFoundException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.LobbyInfo[] getAvailableLobbies () throws Server.Exceptions.LostConnectionException, Server.Exceptions.NoSessionsFoundException;

  // Game stats
  String getWinRatio (String playerId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NoSuchUserFoundException, Server.Exceptions.NotLoggedInException;
  Server.CommonObjects.GameResult[] getGameHistory (String playerId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException, Server.Exceptions.NoSuchUserFoundException;

  // Connection
  String ping (String userId) throws Server.Exceptions.LostConnectionException, Server.Exceptions.NotLoggedInException;
} // interface PlayerInterfaceOperations
