package Server.PlayerSide;


/**
* Server/PlayerSide/PlayerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerInterface.idl
* Tuesday, May 13, 2025 4:19:17 AM SGT
*/

public abstract class PlayerInterfacePOA extends org.omg.PortableServer.Servant
 implements PlayerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new Integer (0));
    _methods.put ("logout", new Integer (1));
    _methods.put ("createLobby", new Integer (2));
    _methods.put ("joinLobby", new Integer (3));
    _methods.put ("randomConnect", new Integer (4));
    _methods.put ("disconnect", new Integer (5));
    _methods.put ("getAvailableLobbies", new Integer (6));
    _methods.put ("getWinRatio", new Integer (7));
    _methods.put ("getGameHistory", new Integer (8));
    _methods.put ("ping", new Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Authentication
       case 0:  // Server/PlayerSide/PlayerInterface/login
       {
         try {
           Server.CommonInterface.CallBackInterface cb = Server.CommonInterface.CallBackInterfaceHelper.read (in);
           String username = in.read_string ();
           String password = in.read_string ();
           String $result = null;
           $result = this.login (cb, username, password);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.AlreadyLoggedInExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.UserIsBannedException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.UserIsBannedExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // Server/PlayerSide/PlayerInterface/logout
       {
         try {
           String userId = in.read_string ();
           this.logout (userId);
           out = $rh.createReply();
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Lobby management
       case 2:  // Server/PlayerSide/PlayerInterface/createLobby
       {
         try {
           Server.CommonObjects.User host = Server.CommonObjects.UserHelper.read (in);
           String lobbyName = in.read_string ();
           Server.CommonObjects.GameRules rules = Server.CommonObjects.GameRulesHelper.read (in);
           GameSession $result = null;
           $result = this.createLobby (host, lobbyName, rules);
           out = $rh.createReply();
           GameSessionHelper.write (out, $result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.SessionAlreadyMadeException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.SessionAlreadyMadeExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // Server/PlayerSide/PlayerInterface/joinLobby
       {
         try {
           String lobbyId = in.read_string ();
           Server.CommonObjects.User player = Server.CommonObjects.UserHelper.read (in);
           GameSession $result = null;
           $result = this.joinLobby (lobbyId, player);
           out = $rh.createReply();
           GameSessionHelper.write (out, $result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.SessionNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.SessionNotFoundExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.SessionFullException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.SessionFullExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.PlayerAlreadyInSessionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.PlayerAlreadyInSessionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.UserIsBannedException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.UserIsBannedExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // Server/PlayerSide/PlayerInterface/randomConnect
       {
         try {
           Server.CommonObjects.User user = Server.CommonObjects.UserHelper.read (in);
           GameSession $result = null;
           $result = this.randomConnect (user);
           out = $rh.createReply();
           GameSessionHelper.write (out, $result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NoSessionsFoundException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NoSessionsFoundExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.SessionFullException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.SessionFullExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.PlayerAlreadyInSessionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.PlayerAlreadyInSessionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // Server/PlayerSide/PlayerInterface/disconnect
       {
         try {
           String sessionId = in.read_string ();
           String playerId = in.read_string ();
           this.disconnect (sessionId, playerId);
           out = $rh.createReply();
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.SessionNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.SessionNotFoundExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // Server/PlayerSide/PlayerInterface/getAvailableLobbies
       {
         try {
           Server.CommonObjects.LobbyInfo $result[] = null;
           $result = this.getAvailableLobbies ();
           out = $rh.createReply();
           LobbyListHelper.write (out, $result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NoSessionsFoundException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NoSessionsFoundExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Game stats
       case 7:  // Server/PlayerSide/PlayerInterface/getWinRatio
       {
         try {
           String playerId = in.read_string ();
           String $result = null;
           $result = this.getWinRatio (playerId);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NoSuchUserFoundException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NoSuchUserFoundExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // Server/PlayerSide/PlayerInterface/getGameHistory
       {
         try {
           String playerId = in.read_string ();
           Server.CommonObjects.GameResult $result[] = null;
           $result = this.getGameHistory (playerId);
           out = $rh.createReply();
           GameHistoryHelper.write (out, $result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NoSuchUserFoundException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NoSuchUserFoundExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Connection
       case 9:  // Server/PlayerSide/PlayerInterface/ping
       {
         try {
           String userId = in.read_string ();
           String $result = null;
           $result = this.ping (userId);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (Server.Exceptions.LostConnectionException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.LostConnectionExceptionHelper.write (out, $ex);
         } catch (Server.Exceptions.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server.Exceptions.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server/PlayerSide/PlayerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PlayerInterface _this() 
  {
    return PlayerInterfaceHelper.narrow(
    super._this_object());
  }

  public PlayerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class PlayerInterfacePOA
