package GameServer;

/**
* GameServer/GameServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/

public final class GameServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.GameServerInterface value = null;

  public GameServerInterfaceHolder ()
  {
  }

  public GameServerInterfaceHolder (GameServer.GameServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.GameServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.GameServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.GameServerInterfaceHelper.type ();
  }

}
