package GameServer;


/**
* GameServer/GameServerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/

abstract public class GameServerInterfaceHelper
{
  private static String  _id = "IDL:GameServer/GameServerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, GameServer.GameServerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameServer.GameServerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameServer.GameServerInterfaceHelper.id (), "GameServerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameServer.GameServerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameServerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameServer.GameServerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameServer.GameServerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameServer.GameServerInterface)
      return (GameServer.GameServerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameServer._GameServerInterfaceStub stub = new GameServer._GameServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameServer.GameServerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameServer.GameServerInterface)
      return (GameServer.GameServerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameServer._GameServerInterfaceStub stub = new GameServer._GameServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
