package GameServer;


/**
* GameServer/GameServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/

public interface GameServerInterfaceOperations 
{

  // Authentication methods
  String authenticate (String username, String password);
  void logout (String username);
  boolean verifyCredentials (String username, String password);
  String generateUniqueToken ();
  String validateToken (String token);

  // Game management methods
  String createGame (String token);
  boolean joinGame (String token, String gameId);
  void cancelGame (String token, String gameId);

  // Game play methods
  boolean submitGuess (String token, String gameId, char letter);
  String getGameStatus (String token, String gameId);

  // Leaderboard methods
  String getLeaderboard ();

  // Admin methods
  boolean addPlayer (String token, String username, String password);
  boolean removePlayer (String token, String username);
  boolean updatePlayer (String token, String username, String newPassword);
  String searchPlayer (String token, String searchTerm);
  boolean setWaitingTime (String token, int seconds);
  boolean setRoundDuration (String token, int seconds);
} // interface GameServerInterfaceOperations
