package GameServer;


/**
* GameServer/GameServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/

public interface GameServerInterface extends GameServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameServerInterface
