package Server.CommonInterface;


/**
* Server/CommonInterface/CallBackInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommonInterface.idl
* Tuesday, May 13, 2025 4:19:27 AM SGT
*/

public interface CallBackInterfaceOperations 
{
  void receivePing (String client_id);
  void heartbeat ();

  // Game-related callbacks
  void updatePlayerList (String[] players);
  void gameStarted ();
  void yourTurn ();
  void wordToGuess (String wordWithBlanks);

  // e.g., "H _ N G M _ N"
  void guessResult (boolean correct, char letter);
  void gameEnded (Server.CommonObjects.GameResult result);
} // interface CallBackInterfaceOperations
