package Server.CommonInterface;


/**
* Server/CommonInterface/CallBackInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommonInterface.idl
* Tuesday, May 13, 2025 4:19:27 AM SGT
*/

public interface CallBackInterface extends CallBackInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallBackInterface
