package GameServer.GameServerInterfacePackage;

/**
* GameServer/GameServerInterfacePackage/AlreadyLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/


// Exception for when player is already logged in
public final class AlreadyLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.GameServerInterfacePackage.AlreadyLoggedInException value = null;

  public AlreadyLoggedInExceptionHolder ()
  {
  }

  public AlreadyLoggedInExceptionHolder (GameServer.GameServerInterfacePackage.AlreadyLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.GameServerInterfacePackage.AlreadyLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.GameServerInterfacePackage.AlreadyLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.GameServerInterfacePackage.AlreadyLoggedInExceptionHelper.type ();
  }

}
