package GameServer.GameServerInterfacePackage;


/**
* GameServer/GameServerInterfacePackage/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/


// Exception for when player is already logged in
public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{
  public String message = null;

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor

  public AlreadyLoggedInException (String _message)
  {
    super(AlreadyLoggedInExceptionHelper.id());
    message = _message;
  } // ctor


  public AlreadyLoggedInException (String $reason, String _message)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class AlreadyLoggedInException
