package GameServer.GameServerInterfacePackage;

/**
* GameServer/GameServerInterfacePackage/GameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/


// Exception for when game is full or not found
public final class GameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.GameServerInterfacePackage.GameException value = null;

  public GameExceptionHolder ()
  {
  }

  public GameExceptionHolder (GameServer.GameServerInterfacePackage.GameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.GameServerInterfacePackage.GameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.GameServerInterfacePackage.GameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.GameServerInterfacePackage.GameExceptionHelper.type ();
  }

}
