package GameServer.GameServerInterfacePackage;


/**
* GameServer/GameServerInterfacePackage/GameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Thursday, May 8, 2025 3:33:01 PM SGT
*/


// Exception for when game is full or not found
public final class GameException extends org.omg.CORBA.UserException
{
  public String message = null;

  public GameException ()
  {
    super(GameExceptionHelper.id());
  } // ctor

  public GameException (String _message)
  {
    super(GameExceptionHelper.id());
    message = _message;
  } // ctor


  public GameException (String $reason, String _message)
  {
    super(GameExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class GameException
