package Server.CommonObjects;


/**
* Server/CommonObjects/GameRules.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommonInterface.idl
* Tuesday, May 13, 2025 4:19:27 AM SGT
*/

public final class GameRules implements org.omg.CORBA.portable.IDLEntity
{
  public int timeToGuess = (int)0;

  // Time in seconds for each turn
  public int maxRounds = (int)0;

  // Maximum number of rounds
  public int maxGuesses = (int)0;

  // Maximum wrong guesses allowed
  public int minPlayers = (int)0;

  // Minimum players required to start
  public int maxPlayers = (int)0;

  public GameRules ()
  {
  } // ctor

  public GameRules (int _timeToGuess, int _maxRounds, int _maxGuesses, int _minPlayers, int _maxPlayers)
  {
    timeToGuess = _timeToGuess;
    maxRounds = _maxRounds;
    maxGuesses = _maxGuesses;
    minPlayers = _minPlayers;
    maxPlayers = _maxPlayers;
  } // ctor

} // class GameRules
