package Server.CommonObjects;


/**
* Server/CommonObjects/GameRulesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommonInterface.idl
* Tuesday, May 13, 2025 4:19:27 AM SGT
*/

abstract public class GameRulesHelper
{
  private static String  _id = "IDL:Server/CommonObjects/GameRules:1.0";

  public static void insert (org.omg.CORBA.Any a, GameRules that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameRules extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "timeToGuess",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "maxRounds",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "maxGuesses",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "minPlayers",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "maxPlayers",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (GameRulesHelper.id (), "GameRules", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameRules read (org.omg.CORBA.portable.InputStream istream)
  {
    GameRules value = new GameRules ();
    value.timeToGuess = istream.read_long ();
    value.maxRounds = istream.read_long ();
    value.maxGuesses = istream.read_long ();
    value.minPlayers = istream.read_long ();
    value.maxPlayers = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameRules value)
  {
    ostream.write_long (value.timeToGuess);
    ostream.write_long (value.maxRounds);
    ostream.write_long (value.maxGuesses);
    ostream.write_long (value.minPlayers);
    ostream.write_long (value.maxPlayers);
  }

}
