package Server.CommonObjects;


/**
* Server/CommonObjects/LobbyInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommonInterface.idl
* Tuesday, May 13, 2025 4:19:27 AM SGT
*/

public final class LobbyInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String lobbyId = null;
  public String hostName = null;
  public int currentPlayers = (int)0;
  public int maxPlayers = (int)0;
  public boolean isPrivate = false;
  public boolean gameStarted = false;

  public LobbyInfo ()
  {
  } // ctor

  public LobbyInfo (String _lobbyId, String _hostName, int _currentPlayers, int _maxPlayers, boolean _isPrivate, boolean _gameStarted)
  {
    lobbyId = _lobbyId;
    hostName = _hostName;
    currentPlayers = _currentPlayers;
    maxPlayers = _maxPlayers;
    isPrivate = _isPrivate;
    gameStarted = _gameStarted;
  } // ctor

} // class LobbyInfo
