package Server.CommonObjects;


/**
* Server/CommonObjects/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommonInterface.idl
* Tuesday, May 13, 2025 4:19:27 AM SGT
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String userId = null;
  public String displayName = null;
  public String password = null;
  public String userType = null;

  public User ()
  {
  } // ctor

  public User (String _userId, String _displayName, String _password, String _userType)
  {
    userId = _userId;
    displayName = _displayName;
    password = _password;
    userType = _userType;
  } // ctor

} // class User
