package Server.Exceptions;

/**
* Server/Exceptions/NoSessionsFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/

public final class NoSessionsFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public NoSessionsFoundException value = null;

  public NoSessionsFoundExceptionHolder ()
  {
  }

  public NoSessionsFoundExceptionHolder (NoSessionsFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NoSessionsFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NoSessionsFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NoSessionsFoundExceptionHelper.type ();
  }

}
