package Server.Exceptions;


/**
* Server/Exceptions/NoSessionsFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/

public final class NoSessionsFoundException extends org.omg.CORBA.UserException
{
  public String message = null;

  public NoSessionsFoundException ()
  {
    super(NoSessionsFoundExceptionHelper.id());
  } // ctor

  public NoSessionsFoundException (String _message)
  {
    super(NoSessionsFoundExceptionHelper.id());
    message = _message;
  } // ctor


  public NoSessionsFoundException (String $reason, String _message)
  {
    super(NoSessionsFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NoSessionsFoundException
