package Server.Exceptions;

/**
* Server/Exceptions/NotYourTurnExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/


// Gameplay exceptions
public final class NotYourTurnExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public NotYourTurnException value = null;

  public NotYourTurnExceptionHolder ()
  {
  }

  public NotYourTurnExceptionHolder (NotYourTurnException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotYourTurnExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotYourTurnExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotYourTurnExceptionHelper.type ();
  }

}
