package Server.Exceptions;


/**
* Server/Exceptions/NotYourTurnException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/


// Gameplay exceptions
public final class NotYourTurnException extends org.omg.CORBA.UserException
{
  public String message = null;

  public NotYourTurnException ()
  {
    super(NotYourTurnExceptionHelper.id());
  } // ctor

  public NotYourTurnException (String _message)
  {
    super(NotYourTurnExceptionHelper.id());
    message = _message;
  } // ctor


  public NotYourTurnException (String $reason, String _message)
  {
    super(NotYourTurnExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NotYourTurnException
