package Server.Exceptions;


/**
* Server/Exceptions/PlayerAlreadyInSessionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/

public final class PlayerAlreadyInSessionException extends org.omg.CORBA.UserException
{
  public String message = null;

  public PlayerAlreadyInSessionException ()
  {
    super(PlayerAlreadyInSessionExceptionHelper.id());
  } // ctor

  public PlayerAlreadyInSessionException (String _message)
  {
    super(PlayerAlreadyInSessionExceptionHelper.id());
    message = _message;
  } // ctor


  public PlayerAlreadyInSessionException (String $reason, String _message)
  {
    super(PlayerAlreadyInSessionExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class PlayerAlreadyInSessionException
