package Server.Exceptions;


/**
* Server/Exceptions/SessionAlreadyMadeException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/


// Lobby/game session exceptions
public final class SessionAlreadyMadeException extends org.omg.CORBA.UserException
{
  public String message = null;

  public SessionAlreadyMadeException ()
  {
    super(SessionAlreadyMadeExceptionHelper.id());
  } // ctor

  public SessionAlreadyMadeException (String _message)
  {
    super(SessionAlreadyMadeExceptionHelper.id());
    message = _message;
  } // ctor


  public SessionAlreadyMadeException (String $reason, String _message)
  {
    super(SessionAlreadyMadeExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class SessionAlreadyMadeException
