package Server.Exceptions;

/**
* Server/Exceptions/SessionAlreadyMadeExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/


// Lobby/game session exceptions
public final class SessionAlreadyMadeExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public SessionAlreadyMadeException value = null;

  public SessionAlreadyMadeExceptionHolder ()
  {
  }

  public SessionAlreadyMadeExceptionHolder (SessionAlreadyMadeException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SessionAlreadyMadeExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SessionAlreadyMadeExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SessionAlreadyMadeExceptionHelper.type ();
  }

}
