package Server.Exceptions;


/**
* Server/Exceptions/UserIsBannedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/

public final class UserIsBannedException extends org.omg.CORBA.UserException
{
  public String message = null;

  public UserIsBannedException ()
  {
    super(UserIsBannedExceptionHelper.id());
  } // ctor

  public UserIsBannedException (String _message)
  {
    super(UserIsBannedExceptionHelper.id());
    message = _message;
  } // ctor


  public UserIsBannedException (String $reason, String _message)
  {
    super(UserIsBannedExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class UserIsBannedException
