package Server.Exceptions;

/**
* Server/Exceptions/UserIsBannedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/

public final class UserIsBannedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public UserIsBannedException value = null;

  public UserIsBannedExceptionHolder ()
  {
  }

  public UserIsBannedExceptionHolder (UserIsBannedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UserIsBannedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UserIsBannedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UserIsBannedExceptionHelper.type ();
  }

}
