package Server.Exceptions;

/**
* Server/Exceptions/WrongGuessExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Tuesday, May 13, 2025 4:19:36 AM SGT
*/

public final class WrongGuessExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WrongGuessException value = null;

  public WrongGuessExceptionHolder ()
  {
  }

  public WrongGuessExceptionHolder (WrongGuessException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WrongGuessExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WrongGuessExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WrongGuessExceptionHelper.type ();
  }

}
